Default: &defaults
  database: HasHellp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: HasHellp_test.sqlite3
  <<: *defaults

Staging:
  database: HasHellp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: HasHellp_production.sqlite3
  poolsize: 100
  <<: *defaults
